sudo: required
language: generic
services: docker
before_install:
  - sudo pip install csup
  - export RPRE=yrok472
  - export RNAME=nessus_scanner
script:
  - docker build --no-cache . -t nessus_scanner:latest
#  - |
#    csup upload nessus_scanner --tag latest \
#      --consec-name sensors/nessus --consec-tag latest -rp
after_success: ./deploy.sh